### ISSUE TITLE
免越狱版本的证书问题

### ISSUE THREAD

**Issue by STingLee666** [buginux/WeChatRedEnvelop#43]
Hi，想请问下，
如果是使用个人开发者证书，需要先将设备的 UUID 加到 Provisioning Profile 中

此处的个人开发者证书，是要缴纳一年99$的会员吗？还是说只注册不交钱的账号也可以呢？谢谢

**Comment by buginux** [comment]
是需要交费，免费账户是不行的。

**Comment by STingLee666** [comment]
个人证书，企业证书都没有，有没有其他招可以破。。。

**Comment by buginux** [comment]
就我所知，没有。

**Comment by buginux** [comment]
哦，不好意思，那可能是我搞错了。如果确认可以的话，那就可以，我自己没有实验过。

**Comment by Mika368** [comment]
比如说微信的ipa大约40MB左右，经过我一系列操作之后，重新签名生成的ipa只有16MB左右，这正常么？还是说什么情况导致

**Comment by buginux** [comment]
这个不太清楚，我没有具体看过应用的大小。如果能正常使用的话，正常是没啥问题的。

**Comment by objwang** [comment]
xcode 8可以生成免费的证书

**Comment by Smmw** [comment]
我用的xcode8 生成的免费证书  但是在网站上找不到 入口去添加uuid 啊。通过xcode安装报错
![untitled](https://cloud.githubusercontent.com/assets/3632980/21743780/4b3fb874-d544-11e6-8041-ca8104162a56.gif)
这是什么意思啊？第一次接触ios。从周五折腾到现在 就差最后一步了。。

**Comment by Smmw** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3632980/21743789/9047826c-d544-11e6-8891-2f25f9fddedd.gif)

**Comment by Smmw** [comment]
卧槽 图怎么都挂了。。
A WatchKit app within this app is not a valid bundle.
这是报错信息。

**Comment by objwang** [comment]
你看看这个吧 http://www.cnblogs.com/lihaibo-Leao/p/5351690.html

**Comment by Smmw** [comment]
我昨天就是按照这个弄的  现在好了 知道为什么了 我是直接打包签名ipa文件  应该打包签名app文件

**Comment by Mika368** [comment]
我就是签名的app文件，我可以把我的app给你，你用你的证书给我签名一下，看看能不能正常使用，好吗？发自网易邮箱大师
            在2017年01月08日 12:25，Smmw 写道:我昨天就是按照这个弄的  现在好了 知道为什么了 我是直接打包签名ipa文件  应该打包签名app文件

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: 我昨天就是按照这个弄的  现在好了 知道为什么了 我是直接打包签名ipa文件  应该打包签名app文件"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271128968"}}}

**Comment by Smmw** [comment]
@Mika368  你的报错什么啊？我的是xcode免费生成的证书 签了你也用不了

**Comment by Mika368** [comment]
我最后生成的ipa体积是原来的一半左右，这正常么？我有证书的，但是最后不能安装，所以怀疑是证书的问题发自网易邮箱大师
            在2017年01月08日 08:18，objwang 写道:你看看这个吧 http://www.cnblogs.com/lihaibo-Leao/p/5351690.html

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@objwang in #43: 你看看这个吧 http://www.cnblogs.com/lihaibo-Leao/p/5351690.html"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271119849"}}}

**Comment by Mika368** [comment]
我的ipa在6splus   9.3.3提示跟你的一样，但是在6   10.1上提示没有build发自网易邮箱大师
            在2017年01月08日 01:56，Smmw 写道:卧槽 图怎么都挂了。。
A WatchKit app within this app is not a valid bundle.
这是报错信息。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: 卧槽 图怎么都挂了。。\r\nA WatchKit app within this app is not a valid bundle.\r\n这是报错信息。"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271099013"}}}

**Comment by Mika368** [comment]
我的ipa在6splus   9.3.3提示watchkit …，但是在6   10.1上提示没有build发自网易邮箱大师
            在2017年01月10日 16:32，Smmw 写道:@Mika368  你的报错什么啊？我的是xcode免费生成的证书 签了你也用不了

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: @Mika368  你的报错什么啊？我的是xcode免费生成的证书 签了你也用不了"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271515440"}}}

**Comment by Smmw** [comment]
@Mika368  你要删除 wechat.app 里的watch 文件

**Comment by Mika368** [comment]
你可以签名一下，看一下你自己能不能安装使用，排除一下我ipa的问题发自网易邮箱大师
            在2017年01月10日 16:32，Smmw 写道:@Mika368  你的报错什么啊？我的是xcode免费生成的证书 签了你也用不了

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: @Mika368  你的报错什么啊？我的是xcode免费生成的证书 签了你也用不了"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271515440"}}}

**Comment by Smmw** [comment]
@Mika368 我现在手上没有 mac。 我电脑在家里 我现在在单位

**Comment by Mika368** [comment]
watch文件，我应该删除了，我按照教程来的，方便加一下QQ么？1006441417发自网易邮箱大师
            在2017年01月10日 16:37，Smmw 写道:@Mika368 我现在手上没有 mac。 我电脑在家里 我现在在单位

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: @Mika368 我现在手上没有 mac。 我电脑在家里 我现在在单位"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271516466"}}}

**Comment by Smmw** [comment]
@Mika368 教程里没有提到 要删除watch 文件啊

**Comment by Mika368** [comment]
我等下回去再检查一下发自网易邮箱大师
            在2017年01月10日 16:42，Smmw 写道:@Mika368 教程里没有提到 要删除watch 文件啊

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: @Mika368 教程里没有提到 要删除watch 文件啊"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271517350"}}}

**Comment by Mika368** [comment]
我的报错发自网易邮箱大师
            图片在2017年01月10日 16:42，Smmw 写道:@Mika368 教程里没有提到 要删除watch 文件啊

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: @Mika368 教程里没有提到 要删除watch 文件啊"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271517350"}}}

**Comment by Mika368** [comment]
This application is not built for this device.我的watch已经删掉了发自网易邮箱大师
            在2017年01月10日 18:02，Smmw 写道:@Mika368 看不到图片。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: @Mika368 看不到图片。"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271534474"}}}

**Comment by Mika368** [comment]
你可以把我的uuid添加你的证书里面，给我发一个签名的ipa吗？谢谢23c027178489f03a2a08142f78416ba15d1ddfe9
            在2017年01月10日 18:04，马林辉 写道:
        
            This application is not built for this device.我的watch已经删掉了发自网易邮箱大师
            在2017年01月10日 18:02，Smmw 写道:@Mika368 看不到图片。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: @Mika368 看不到图片。"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271534474"}}}

**Comment by Mika368** [comment]
这个2c0300c07a2a4831d4e6f3eb998e3e9d80ee3894发自网易邮箱大师
            在2017年01月15日 16:12，马林辉 写道:
        
            你可以把我的uuid添加你的证书里面，给我发一个签名的ipa吗？谢谢23c027178489f03a2a08142f78416ba15d1ddfe9
            在2017年01月10日 18:04，马林辉 写道:
        
            This application is not built for this device.我的watch已经删掉了发自网易邮箱大师
            在2017年01月10日 18:02，Smmw 写道:@Mika368 看不到图片。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/buginux/WeChatRedEnvelop","title":"buginux/WeChatRedEnvelop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/buginux/WeChatRedEnvelop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Smmw in #43: @Mika368 看不到图片。"}],"action":{"name":"View Issue","url":"https://github.com/buginux/WeChatRedEnvelop/issues/43#issuecomment-271534474"}}}
